In [38]:
#Import dependencies
import pandas as pd
import datetime as dt
import numpy as np

In [39]:
nba_draft = pd.read_csv("2007-2016_nba_draft_rd1-2.csv", engine='python')
nba_draft.head()

,Rk,Year,Lg,Rd,Pk,Tm,Player,Age,Pos,Born,...,TRB,AST,STL,BLK,FG%,2P%,3P%,FT%,WS,WS/48
0,1,2007,NBA,1,2,SEA,Kevin Durant,18.276,F-G,us,...,7.1,4.1,1.1,1.1,0.493,0.532,0.381,0.883,141.7,0.217
1,2,2009,NBA,1,3,OKC,James Harden,19.308,G,us,...,5.3,6.3,1.6,0.5,0.443,0.508,0.364,0.858,131.9,0.226
2,3,2009,NBA,1,7,GSW,Stephen Curry,21.108,G,us,...,4.5,6.6,1.7,0.2,0.476,0.515,0.435,0.905,103.1,0.206
3,4,2008,NBA,1,4,SEA,Russell Westbrook,19.231,G,us,...,7.1,8.3,1.7,0.3,0.436,0.468,0.304,0.801,100.5,0.161
4,5,2007,NBA,1,3,ATL,Al Horford,21.030,C-F,do,...,8.3,3.3,0.8,1.2,0.520,0.544,0.361,0.753,89.8,0.158

In [40]:
draft_condensed = nba_draft[["Player", "Year", "Tm", "College"]]
draft_condensed.head()

              Player  Year   Tm        College
0       Kevin Durant  2007  SEA          Texas
1       James Harden  2009  OKC  Arizona State
2      Stephen Curry  2009  GSW       Davidson
3  Russell Westbrook  2008  SEA           UCLA
4         Al Horford  2007  ATL        Florida

In [41]:
first_year = draft_condensed.loc[draft_condensed["Year"] == 2007].copy()

In [42]:
first_year

                 Player  Year   Tm             College
0          Kevin Durant  2007  SEA               Texas
4            Al Horford  2007  ATL             Florida
6            Marc Gasol  2007  LAL                 NaN
12          Mike Conley  2007  MEM          Ohio State
20          Joakim Noah  2007  CHI             Florida
23       Thaddeus Young  2007  PHI        Georgia Tech
51         Jared Dudley  2007  CHA      Boston College
58           Jeff Green  2007  BOS          Georgetown
65          Carl Landry  2007  SEA              Purdue
70        Arron Afflalo  2007  DET                UCLA
77      Marco Belinelli  2007  GSW                 NaN
83      Wilson Chandler  2007  NYK              DePaul
85       Ramon Sessions  2007  MIL              Nevada
86       Rodney Stuckey  2007  DET  Eastern Washington
96       Brandan Wright  2007  CHA                 UNC
102      Tiago Splitter  2007  SAS                 NaN
116       Spencer Hawes  2007  SAC          Washington
118        Corey Brewer  2007  MIN             Florida
142        Aaron Brooks  2007  HOU              Oregon
145          Nick Young  2007  WAS                 USC
146          Glen Davis  2007  SEA                 LSU
148      Josh McRoberts  2007  POR                Duke
183      Rudy Fernâ€¡ndez  2007  PHO                 NaN
184         Jason Smith  2007  MIA      Colorado State
246           Greg Oden  2007  POR          Ohio State
257          Aaron Gray  2007  CHI                Pitt
260         Al Thornton  2007  LAC       Florida State
278        Daequan Cook  2007  PHI          Ohio State
291     Dominic McGuire  2007  WAS        Fresno State
294       Julian Wright  2007  NOK              Kansas
312         Yi Jianlian  2007  MIL                 NaN
313       Sean Williams  2007  NJN      Boston College
340            Acie Law  2007  ATL           Texas A&M
360      Kyrylo Fesenko  2007  PHI                 NaN
365        Nick Fazekas  2007  DAL              Nevada
370       Chris Richard  2007  MIN             Florida
387       Alando Tucker  2007  PHO           Wisconsin
388         Gabe Pruitt  2007  BOS                 USC
395      StÅ½phane Lasme  2007  GSW               UMass
420  Javaris Crittenton  2007  LAL        Georgia Tech
421       Derrick Byars  2007  POR          Vanderbilt
432       Morris Almond  2007  UTA     Rice University
433   Jermareo Davidson  2007  GSW             Alabama
434       JamesOn Curry  2007  CHI      Oklahoma State
458     Marcus Williams  2007  SAS             Arizona
459             Sun Yue  2007  LAL                 NaN
460       Taurean Green  2007  POR             Florida
479    Demetris Nichols  2007  POR            Syracuse
480     D.J. Strawberry  2007  PHO            Maryland
513     Petteri Koponen  2007  PHI                 NaN
514        Stanko Bara_  2007  MIA                 NaN
515        Adam Haluska  2007  NOK                Iowa
516      Reyshawn Terry  2007  ORL                 UNC
517        Jared Jordan  2007  LAC      Marist College
518   Renaldas Seibutis  2007  DAL                 NaN
519         Brad Newley  2007  HOU                 NaN
520        Herbert Hill  2007  UTA          Providence
521         Sammy Mejia  2007  DET              DePaul
522  Georgios Printezis  2007  SAS                 NaN
523      Milovan Rakovi  2007  DAL                 NaN

In [43]:
OhSeven_stats = pd.read_csv("stats_2007.csv", engine='python')

In [44]:
OhSeven_stats

,attempted_three_point_field_goals,blocks,slug,personal_fouls,made_three_point_field_goals,attempted_field_goals,made_free_throws,name,minutes_played,turnovers,...,games_started,age,steals,team,points,attempted_free_throws,games_played,assists,offensive_rebounds,defensive_rebounds
0,20,40,abdursh01,243,3,654,170,Shareef Abdur-Rahim,2015,116,...,45,30,53,Team.SACRAMENTO_KINGS,793,234,80,109,122,276
1,1,4,adamsha01,47,0,135,24,Hassan Adams,495,22,...,8,22,17,Team.NEW_JERSEY_NETS,174,36,61,13,35,42
2,15,3,agerma01,27,5,70,20,Maurice Ager,214,15,...,1,22,4,Team.DALLAS_MAVERICKS,69,33,32,7,1,20
3,2,73,aldrila01,186,0,479,83,LaMarcus Aldridge,1392,43,...,22,21,22,Team.PORTLAND_TRAIL_BLAZERS,565,115,63,24,144,168
4,1,16,allenma01,85,0,258,28,Malik Allen,638,21,...,1,28,17,Team.CHICAGO_BULLS,242,34,60,16,42,77
5,443,11,allenra02,113,165,1153,279,Ray Allen*,2219,154,...,55,31,82,Team.SEATTLE_SUPERSONICS,1454,309,55,228,57,190
6,33,12,allento01,87,8,259,105,Tony Allen,805,75,...,18,25,49,Team.BOSTON_CELTICS,379,134,33,56,35,89
7,529,10,alstora01,195,192,1020,130,Rafer Alston,3040,170,...,82,30,129,Team.HOUSTON_ROCKETS,1088,177,82,444,29,253
8,0,0,amundlo01,0,0,0,0,Lou Amundson,2,0,...,0,24,0,Team.UTAH_JAZZ,0,0,1,0,0,0
9,0,8,amundlo01,15,0,15,4,Lou Amundson,87,5,...,0,24,1,Team.PHILADELPHIA_76ERS,16,10,10,1,13,15
10,20,0,anderal01,33,5,81,19,Alan Anderson,256,22,...,0,24,7,Team.CHARLOTTE_BOBCATS,98,23,17,21,11,21
11,152,7,anderde01,115,54,294,93,Derek Anderson,1190,56,...,32,32,52,Team.CHARLOTTE_BOBCATS,399,106,50,133,29,84
12,149,23,anthoca01,203,40,1453,459,Carmelo Anthony,2486,234,...,65,22,77,Team.DENVER_NUGGETS,1881,568,65,249,143,248
13,0,2,araujra01,39,0,65,18,Rafael AraÃºjo,248,17,...,0,26,6,Team.UTAH_JAZZ,72,29,28,10,22,44
14,584,13,arenagi01,249,205,1548,606,Gilbert Arenas,2942,236,...,73,25,139,Team.WASHINGTON_WIZARDS,2105,718,74,443,61,277
15,7,19,arizatr01,134,0,371,106,Trevor Ariza,1278,84,...,7,21,59,Team.ORLANDO_MAGIC,506,171,57,65,98,151
16,214,6,armstda01,102,72,377,73,Darrell Armstrong,1275,76,...,4,38,70,Team.INDIANA_PACERS,457,93,81,191,34,101
17,0,26,armsthi01,79,0,125,40,Hilton Armstrong,634,35,...,5,22,12,Team.NEW_ORLEANS_OKLAHOMA_CITY_HORNETS,176,67,56,10,58,91
18,51,2,arroyca01,131,14,478,132,Carlos Arroyo,1304,90,...,5,27,39,Team.ORLANDO_MAGIC,552,166,72,202,31,103
19,306,4,atkinch01,136,116,715,252,Chucky Atkins,2064,127,...,23,32,50,Team.MEMPHIS_GRIZZLIES,988,311,75,346,18,121
20,0,0,augusja01,2,0,3,0,James Augustine,7,0,...,0,22,0,Team.ORLANDO_MAGIC,2,0,2,2,1,2
21,79,10,azubuke01,49,34,220,61,Kelenna Azubuike,669,39,...,9,23,22,Team.GOLDEN_STATE_WARRIORS,291,78,41,28,26,68
22,27,44,balkmre01,146,5,275,51,Renaldo Balkman,1064,49,...,1,22,57,Team.NEW_YORK_KNICKS,334,90,68,44,97,197
23,29,3,banksma01,70,5,196,48,Marcus Banks,503,40,...,1,25,23,Team.PHOENIX_SUNS,221,60,45,60,10,28
24,438,15,barbole01,210,190,1111,196,Leandro Barbosa,2613,146,...,18,24,96,Team.PHOENIX_SUNS,1444,232,80,317,22,192
25,21,1,bareajo01,19,6,78,16,J.J. Barea,191,14,...,1,22,1,Team.DALLAS_MAVERICKS,78,24,33,24,7,18
26,268,53,bargnan01,180,100,625,117,Andrea Bargnani,1629,107,...,2,21,32,Team.TORONTO_RAPTORS,751,142,65,50,52,203
27,290,41,barnema02,188,106,628,90,Matt Barnes,1813,105,...,23,26,73,Team.GOLDEN_STATE_WARRIORS,746,123,76,156,91,259
28,0,0,barrean01,4,0,8,0,Andre Barrett,29,4,...,0,24,0,Team.CHICAGO_BULLS,8,0,6,7,1,4
29,1,4,barroea01,21,0,83,17,Earl Barron,203,11,...,0,25,6,Team.MIAMI_HEAT,65,18,28,5,19,22
30,287,12,barrybr01,88,128,425,103,Brent Barry,1631,61,...,28,35,56,Team.SAN_ANTONIO_SPURS,635,117,75,138,17,143
31,1,3,bassbr01,16,0,44,12,Brandon Bass,162,10,...,3,21,2,Team.NEW_ORLEANS_OKLAHOMA_CITY_HORNETS,42,16,21,3,13,30
32,7,18,bastoma01,65,3,76,37,Maceo Baston,405,32,...,2,31,12,Team.INDIANA_PACERS,138,47,47,16,21,53
33,0,0,batises01,13,0,16,4,Esteban Batista,81,4,...,0,23,3,Team.ATLANTA_HAWKS,20,7,13,4,7,23
34,1,30,battito01,185,0,360,52,Tony Battie,1575,61,...,66,30,29,Team.ORLANDO_MAGIC,404,77,66,35,92,252
35,373,60,battish01,190,157,654,88,Shane Battier,2988,72,...,82,28,79,Team.HOUSTON_ROCKETS,829,113,82,175,67,271
36,361,4,bellch01,213,127,974,131,Charlie Bell,2848,104,...,64,27,97,Team.MILWAUKEE_BUCKS,1110,168,82,247,57,181
37,496,22,bellra01,233,205,950,118,Raja Bell,2917,83,...,78,30,50,Team.PHOENIX_SUNS,1143,152,78,196,48,203
38,481,6,bibbymi01,139,173,1166,288,Mike Bibby,2784,197,...,82,28,88,Team.SACRAMENTO_KINGS,1403,347,82,388,39,224

In [45]:
OhSevenCondensed = OhSeven_stats[["name", "points", "assists", "defensive_rebounds", "offensive_rebounds"]]
OhSevenCondensed.head()

,name,points,assists,defensive_rebounds,offensive_rebounds
0,Shareef Abdur-Rahim,793,109,276,122
1,Hassan Adams,174,13,42,35
2,Maurice Ager,69,7,20,1
3,LaMarcus Aldridge,565,24,168,144
4,Malik Allen,242,16,77,42

In [46]:
OhEight_stats = pd.read_csv("stats_2008.csv", engine='python')

In [47]:
OhEight_stats

,attempted_three_point_field_goals,blocks,slug,personal_fouls,made_three_point_field_goals,attempted_field_goals,made_free_throws,name,minutes_played,turnovers,...,games_started,age,steals,team,points,attempted_free_throws,games_played,assists,offensive_rebounds,defensive_rebounds
0,0,0,abdursh01,9,0,14,4,Shareef Abdur-Rahim,51,1,...,0,31,1,Team.SACRAMENTO_KINGS,10,4,6,4,6,4
1,48,8,afflaar01,83,10,241,68,Arron Afflalo,970,34,...,9,22,31,Team.DETROIT_PISTONS,276,87,75,52,36,101
2,8,1,agerma01,11,0,27,5,Maurice Ager,77,3,...,3,23,0,Team.DALLAS_MAVERICKS,15,6,12,4,1,3
3,11,0,agerma01,6,3,38,1,Maurice Ager,88,3,...,0,23,0,Team.NEW_JERSEY_NETS,36,6,14,4,3,6
4,34,0,ahearbl01,20,10,57,30,Blake Ahearn,177,16,...,0,23,6,Team.MIAMI_HEAT,70,31,12,19,1,18
5,7,94,aldrila01,240,1,1160,227,LaMarcus Aldridge,2649,126,...,76,22,55,Team.PORTLAND_TRAIL_BLAZERS,1350,298,76,122,220,358
6,2,21,allenma01,89,1,261,12,Malik Allen,763,32,...,12,29,15,Team.NEW_JERSEY_NETS,261,13,48,29,42,86
7,0,10,allenma01,60,0,66,11,Malik Allen,333,13,...,4,29,4,Team.DALLAS_MAVERICKS,77,12,25,15,24,44
8,452,16,allenra02,147,180,986,215,Ray Allen*,2624,127,...,73,32,65,Team.BOSTON_CELTICS,1273,237,73,225,75,193
9,57,21,allento01,168,18,389,138,Tony Allen,1373,109,...,11,26,62,Team.BOSTON_CELTICS,494,181,75,114,34,134
10,0,0,allrela01,1,0,4,1,Lance Allred,10,0,...,0,26,0,Team.CLEVELAND_CAVALIERS,3,2,3,0,0,1
11,4,0,almonmo01,5,1,15,4,Morris Almond,39,2,...,0,22,1,Team.UTAH_JAZZ,13,6,9,3,0,2
12,407,18,alstora01,139,143,924,98,Rafer Alston,2526,160,...,74,31,98,Team.HOUSTON_ROCKETS,969,137,74,392,28,232
13,0,1,amundlo01,13,0,16,2,Lou Amundson,64,2,...,0,25,1,Team.PHILADELPHIA_76ERS,18,7,16,0,7,5
14,0,4,anderch01,6,0,7,2,Chris Andersen,34,1,...,0,29,0,Team.NEW_ORLEANS_HORNETS,6,4,5,0,2,7
15,52,1,anderde01,49,19,125,28,Derek Anderson,396,25,...,0,33,12,Team.CHARLOTTE_BOBCATS,141,38,28,44,9,43
16,164,39,anthoca01,253,58,1481,464,Carmelo Anthony,2806,253,...,77,23,98,Team.DENVER_NUGGETS,1978,590,77,259,178,393
17,0,31,anthojo01,55,0,60,29,Joel Anthony,498,17,...,1,25,9,Team.MIAMI_HEAT,85,49,24,3,38,55
18,78,1,arenagi01,30,22,196,74,Gilbert Arenas,425,49,...,8,26,23,Team.WASHINGTON_WIZARDS,252,96,13,66,6,45
19,3,3,arizatr01,9,0,31,8,Trevor Ariza,115,5,...,0,22,5,Team.ORLANDO_MAGIC,36,15,11,8,5,19
20,15,8,arizatr01,36,5,105,41,Trevor Ariza,431,18,...,3,22,26,Team.LOS_ANGELES_LAKERS,156,60,24,36,25,59
21,69,2,armstda01,53,23,110,20,Darrell Armstrong,549,41,...,2,39,28,Team.NEW_JERSEY_NETS,123,30,50,73,17,50
22,0,34,armsthi01,130,0,148,44,Hilton Armstrong,732,59,...,3,23,15,Team.NEW_ORLEANS_HORNETS,178,70,65,23,65,98
23,84,2,arroyca01,85,29,348,87,Carlos Arroyo,1269,77,...,20,28,26,Team.ORLANDO_MAGIC,430,102,62,219,10,103
24,79,1,atkinch01,27,25,122,4,Chucky Atkins,352,10,...,0,33,9,Team.DENVER_NUGGETS,113,9,24,47,3,28
25,0,2,augusja01,18,0,34,4,James Augustine,149,6,...,0,23,5,Team.ORLANDO_MAGIC,40,8,25,2,16,14
26,195,34,azubuke01,159,71,587,99,Kelenna Azubuike,1732,58,...,17,24,45,Team.GOLDEN_STATE_WARRIORS,692,138,81,75,107,217
27,12,30,balkmre01,132,1,186,41,Renaldo Balkman,952,37,...,0,23,44,Team.NEW_YORK_KNICKS,224,95,65,40,83,133
28,65,8,banksma01,38,25,109,12,Marcus Banks,310,16,...,1,26,8,Team.PHOENIX_SUNS,125,16,24,25,3,17
29,37,5,banksma01,27,15,82,15,Marcus Banks,259,21,...,2,26,6,Team.MIAMI_HEAT,114,19,12,36,1,24
30,422,18,barbole01,195,164,1021,175,Leandro Barbosa,2421,117,...,12,25,75,Team.PHOENIX_SUNS,1283,213,82,216,40,191
31,54,1,bareajo01,48,21,170,28,J.J. Barea,460,35,...,9,23,14,Team.DALLAS_MAVERICKS,191,35,44,58,4,43
32,261,37,bargnan01,211,90,725,142,Andrea Bargnani,1861,88,...,53,22,23,Team.TORONTO_RAPTORS,792,169,78,89,50,238
33,181,36,barnema02,159,53,442,59,Matt Barnes,1414,85,...,18,27,48,Team.GOLDEN_STATE_WARRIORS,486,79,73,139,94,230
34,3,0,barrean01,1,1,5,1,Andre Barrett,25,1,...,0,25,0,Team.LOS_ANGELES_CLIPPERS,6,2,4,7,0,1
35,13,8,barroea01,114,1,327,61,Earl Barron,889,48,...,15,26,19,Team.MIAMI_HEAT,326,87,46,29,67,131
36,112,3,barrybr01,43,48,160,19,Brent Barry,554,18,...,1,36,17,Team.SAN_ANTONIO_SPURS,221,20,31,54,12,43
37,4,48,bassbr01,150,0,493,162,Brandon Bass,1557,82,...,1,22,22,Team.DALLAS_MAVERICKS,654,197,79,58,120,227
38,0,4,bastoma01,20,0,25,7,Maceo Baston,103,4,...,2,32,2,Team.TORONTO_RAPTORS,41,10,15,3,9,17
39,369,90,battish01,196,139,619,75,Shane Battier,2907,78,...,78,29,77,Team.HOUSTON_ROCKETS,744,101,80,155,131,276
40,41,0,belinma01,15,16,93,7,Marco Belinelli,241,12,...,0,21,5,Team.GOLDEN_STATE_WARRIORS,95,9,33,15,3,11
41,217,2,bellch01,121,74,486,70,Charlie Bell,1628,76,...,5,28,52,Team.MILWAUKEE_BUCKS,514,87,68,210,31,136
42,439,27,bellra01,220,176,753,79,Raja Bell,2646,65,...,75,31,54,Team.PHOENIX_SUNS,889,91,75,168,47,227
43,61,2,bibbymi01,34,24,192,23,Mike Bibby,473,38,...,12,29,19,Team.SACRAMENTO_KINGS,203,31,15,75,11,45
44,187,2,bibbymi01,63,69,411,55,Mike Bibby,1100,81,...,32,29,35,Team.ATLANTA_HAWKS,464,69,33,215,5,99

In [48]:
OhEightCondensed = OhEight_stats[["name", "points", "assists", "defensive_rebounds", "offensive_rebounds"]]
OhEightCondensed.head()

,name,points,assists,defensive_rebounds,offensive_rebounds
0,Shareef Abdur-Rahim,10,4,4,6
1,Arron Afflalo,276,52,101,36
2,Maurice Ager,15,4,3,1
3,Maurice Ager,36,4,6,3
4,Blake Ahearn,70,19,18,1

In [49]:
pd.merge(OhSevenCondensed.reset_index(), OhEightCondensed.reset_index(), on=['name'])

,index_x,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,index_y,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y
0,0,Shareef Abdur-Rahim,793,109,276,122,0,10,4,4,6
1,2,Maurice Ager,69,7,20,1,2,15,4,3,1
2,2,Maurice Ager,69,7,20,1,3,36,4,6,3
3,3,LaMarcus Aldridge,565,24,168,144,5,1350,122,358,220
4,4,Malik Allen,242,16,77,42,6,261,29,86,42
5,4,Malik Allen,242,16,77,42,7,77,15,44,24
6,5,Ray Allen*,1454,228,190,57,8,1273,225,193,75
7,6,Tony Allen,379,56,89,35,9,494,114,134,34
8,7,Rafer Alston,1088,444,253,29,12,969,392,232,28
9,8,Lou Amundson,0,0,0,0,13,18,0,5,7
10,9,Lou Amundson,16,1,15,13,13,18,0,5,7
11,11,Derek Anderson,399,133,84,29,15,141,44,43,9
12,12,Carmelo Anthony,1881,249,248,143,16,1978,259,393,178
13,14,Gilbert Arenas,2105,443,277,61,18,252,66,45,6
14,15,Trevor Ariza,506,65,151,98,19,36,8,19,5
15,15,Trevor Ariza,506,65,151,98,20,156,36,59,25
16,16,Darrell Armstrong,457,191,101,34,21,123,73,50,17
17,17,Hilton Armstrong,176,10,91,58,22,178,23,98,65
18,18,Carlos Arroyo,552,202,103,31,23,430,219,103,10
19,19,Chucky Atkins,988,346,121,18,24,113,47,28,3
20,20,James Augustine,2,2,2,1,25,40,2,14,16
21,21,Kelenna Azubuike,291,28,68,26,26,692,75,217,107
22,22,Renaldo Balkman,334,44,197,97,27,224,40,133,83
23,23,Marcus Banks,221,60,28,10,28,125,25,17,3
24,23,Marcus Banks,221,60,28,10,29,114,36,24,1
25,24,Leandro Barbosa,1444,317,192,22,30,1283,216,191,40
26,25,J.J. Barea,78,24,18,7,31,191,58,43,4
27,26,Andrea Bargnani,751,50,203,52,32,792,89,238,50
28,27,Matt Barnes,746,156,259,91,33,486,139,230,94
29,28,Andre Barrett,8,7,4,1,34,6,7,1,0
30,29,Earl Barron,65,5,22,19,35,326,29,131,67
31,30,Brent Barry,635,138,143,17,36,221,54,43,12
32,31,Brandon Bass,42,3,30,13,37,654,58,227,120
33,32,Maceo Baston,138,16,53,21,38,41,3,17,9
34,35,Shane Battier,829,175,271,67,39,744,155,276,131
35,36,Charlie Bell,1110,247,181,57,41,514,210,136,31
36,37,Raja Bell,1143,196,203,48,42,889,168,227,47
37,38,Mike Bibby,1403,388,224,39,43,203,75,45,11
38,38,Mike Bibby,1403,388,224,39,44,464,215,99,5

In [50]:
OhNine_stats = pd.read_csv("stats_2009.csv", engine='python')

In [51]:
OhNine_stats

,attempted_three_point_field_goals,blocks,slug,personal_fouls,made_three_point_field_goals,attempted_field_goals,made_free_throws,name,minutes_played,turnovers,...,games_started,age,steals,team,points,attempted_free_throws,games_played,assists,offensive_rebounds,defensive_rebounds
0,4,1,ackeral01,0,0,11,1,Alex Acker,20,0,...,0,26,2,Team.DETROIT_PISTONS,9,2,7,1,0,2
1,16,3,ackeral01,9,7,65,4,Alex Acker,179,7,...,0,26,3,Team.LOS_ANGELES_CLIPPERS,63,8,18,11,8,14
2,0,1,adamsha01,4,0,13,3,Hassan Adams,52,4,...,0,24,1,Team.TORONTO_RAPTORS,11,6,12,1,1,6
3,107,13,afflaar01,144,43,300,58,Arron Afflalo,1234,43,...,8,23,28,Team.DETROIT_PISTONS,363,71,74,44,30,104
4,6,2,agerma01,17,0,43,4,Maurice Ager,97,4,...,0,24,1,Team.NEW_JERSEY_NETS,34,8,20,3,3,7
5,4,0,ahearbl01,3,2,6,2,Blake Ahearn,19,1,...,0,24,1,Team.SAN_ANTONIO_SPURS,8,2,3,2,0,1
6,2,6,ajincal01,34,0,69,20,Alexis AjinÃ§a,182,12,...,4,20,7,Team.CHARLOTTE_BOBCATS,70,28,31,3,9,21
7,28,77,aldrila01,207,7,1243,261,LaMarcus Aldridge,3004,121,...,81,23,77,Team.PORTLAND_TRAIL_BLAZERS,1470,334,81,157,234,371
8,46,29,alexajo01,107,16,245,58,Joe Alexander,716,52,...,0,22,15,Team.MILWAUKEE_BUCKS,278,83,59,42,44,71
9,1,12,allenma01,89,0,170,10,Malik Allen,579,20,...,3,30,7,Team.MILWAUKEE_BUCKS,156,21,49,35,35,68
10,486,13,allenra02,157,199,1040,237,Ray Allen*,2876,134,...,79,33,69,Team.BOSTON_CELTICS,1434,249,79,218,66,212
11,27,23,allento01,98,6,284,79,Tony Allen,887,77,...,2,27,54,Team.BOSTON_CELTICS,359,109,46,66,22,82
12,17,4,almonmo01,31,5,81,21,Morris Almond,255,16,...,1,23,4,Team.UTAH_JAZZ,92,26,25,7,9,27
13,230,7,alstora01,72,80,522,86,Rafer Alston,1591,88,...,48,32,57,Team.HOUSTON_ROCKETS,552,109,48,258,25,119
14,101,3,alstora01,63,32,298,70,Rafer Alston,856,52,...,28,32,51,Team.ORLANDO_MAGIC,348,99,29,148,8,75
15,1,65,amundlo01,154,0,250,53,Lou Amundson,1044,56,...,0,26,32,Team.PHOENIX_SUNS,321,120,76,28,128,142
16,10,175,anderch01,174,2,292,130,Chris Andersen,1460,69,...,1,30,41,Team.DENVER_NUGGETS,452,181,71,31,163,279
17,189,20,anderry01,157,69,407,98,Ryan Anderson,1312,63,...,30,20,44,Team.NEW_JERSEY_NETS,487,116,66,52,104,207
18,170,24,anthoca01,195,63,1207,371,Carmelo Anthony,2277,199,...,66,24,75,Team.DENVER_NUGGETS,1504,468,66,222,106,344
19,0,93,anthojo01,139,0,118,30,Joel Anthony,1048,41,...,28,26,20,Team.MIAMI_HEAT,144,46,65,27,89,108
20,7,1,arenagi01,4,2,23,12,Gilbert Arenas,63,1,...,2,27,0,Team.WASHINGTON_WIZARDS,26,16,2,20,1,8
21,191,24,arizatr01,166,61,596,120,Trevor Ariza,1999,87,...,20,23,137,Team.LOS_ANGELES_LAKERS,729,169,82,145,111,241
22,2,45,armsthi01,181,0,246,62,Hilton Armstrong,1092,80,...,29,24,26,Team.NEW_ORLEANS_HORNETS,338,98,70,29,81,114
23,2,52,arthuda01,206,0,436,40,Darrell Arthur,1464,47,...,64,20,52,Team.MEMPHIS_GRIZZLIES,422,60,76,43,108,238
24,17,1,atkinch01,5,5,27,4,Chucky Atkins,115,10,...,0,34,2,Team.DENVER_NUGGETS,27,4,14,28,0,6
25,40,1,atkinch01,22,10,86,11,Chucky Atkins,297,13,...,0,34,8,Team.OKLAHOMA_CITY_THUNDER,71,12,19,31,5,13
26,246,2,augusdj01,140,108,621,208,D.J. Augustin,1908,119,...,12,21,42,Team.CHARLOTTE_BOBCATS,850,233,72,250,17,116
27,210,50,azubuke01,183,94,845,185,Kelenna Azubuike,2375,95,...,51,25,57,Team.GOLDEN_STATE_WARRIORS,1063,229,74,117,112,258
28,7,23,balkmre01,98,2,197,42,Renaldo Balkman,780,35,...,10,24,47,Team.DENVER_NUGGETS,264,65,53,34,86,117
29,14,2,banksma01,21,2,39,10,Marcus Banks,166,11,...,0,27,10,Team.MIAMI_HEAT,42,15,16,22,0,15
30,5,0,banksma01,5,1,18,1,Marcus Banks,40,3,...,0,27,1,Team.TORONTO_RAPTORS,14,3,6,6,1,2
31,240,7,barbole01,115,90,759,171,Leandro Barbosa,1705,93,...,11,26,82,Team.PHOENIX_SUNS,993,194,70,162,34,147
32,154,5,bareajo01,121,55,557,70,J.J. Barea,1600,105,...,15,24,37,Team.DALLAS_MAVERICKS,617,93,79,269,36,141
33,291,97,bargnan01,242,119,958,221,Andrea Bargnani,2453,135,...,59,23,34,Team.TORONTO_RAPTORS,1202,266,78,94,70,346
34,341,26,barnema02,209,117,674,101,Matt Barnes,2082,130,...,40,28,52,Team.PHOENIX_SUNS,788,136,77,212,79,342
35,131,3,barrybr01,45,49,172,19,Brent Barry,857,48,...,1,37,24,Team.HOUSTON_ROCKETS,208,20,56,78,17,77
36,6,55,bassbr01,140,0,508,182,Brandon Bass,1574,86,...,0,23,27,Team.DALLAS_MAVERICKS,686,210,81,43,129,238
37,1,10,bastoma01,39,0,46,17,Maceo Baston,217,12,...,0,33,6,Team.INDIANA_PACERS,67,27,27,7,22,30
38,9,25,battito01,112,2,323,54,Tony Battie,1202,46,...,3,32,26,Team.ORLANDO_MAGIC,372,82,77,31,92,186
39,237,54,battish01,114,91,354,55,Shane Battier,2031,49,...,59,30,48,Team.HOUSTON_ROCKETS,436,67,60,137,52,233
40,168,40,batumni01,139,62,361,42,Nicolas Batum,1454,50,...,76,20,50,Team.PORTLAND_TRAIL_BLAZERS,426,52,79,74,84,136
41,27,2,bayleje01,81,7,189,83,Jerryd Bayless,655,56,...,0,20,16,Team.PORTLAND_TRAIL_BLAZERS,228,103,53,78,8,49
42,81,37,beaslmi01,184,33,957,186,Michael Beasley,2009,121,...,19,20,41,Team.MIAMI_HEAT,1123,241,81,83,110,329
43,131,1,belinma01,73,52,317,40,Marco Belinelli,882,59,...,23,22,36,Team.GOLDEN_STATE_WARRIORS,372,52,42,88,10,61
44,240,7,bellch01,138,87,524,66,Charlie Bell,1783,76,...,23,29,50,Team.MILWAUKEE_BUCKS,587,80,70,151,32,102
45,94,2,bellra01,57,44,177,16,Raja Bell,712,18,...,22,32,13,Team.PHOENIX_SUNS,212,21,22,29,8,56
46,177,6,bellra01,109,70,507,71,Raja Bell,1603,68,...,44,32,37,Team.CHARLOTTE_BOBCATS,587,81,45,113,33,146
47,428,11,bibbymi01,145,167,1005,135,Mike Bibby,2740,128,...,79,30,98,Team.ATLANTA_HAWKS,1176,171,79,392,38,240

In [52]:
OhNineCondensed = OhNine_stats[["name", "points", "assists", "defensive_rebounds", "offensive_rebounds"]]
OhNineCondensed.head()

            name  points  assists  defensive_rebounds  offensive_rebounds
0     Alex Acker       9        1                   2                   0
1     Alex Acker      63       11                  14                   8
2   Hassan Adams      11        1                   6                   1
3  Arron Afflalo     363       44                 104                  30
4   Maurice Ager      34        3                   7                   3

In [53]:
SevenEight = pd.merge(OhSevenCondensed, OhEightCondensed, on=['name'])
SevenEight

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y
0,Shareef Abdur-Rahim,793,109,276,122,10,4,4,6
1,Maurice Ager,69,7,20,1,15,4,3,1
2,Maurice Ager,69,7,20,1,36,4,6,3
3,LaMarcus Aldridge,565,24,168,144,1350,122,358,220
4,Malik Allen,242,16,77,42,261,29,86,42
5,Malik Allen,242,16,77,42,77,15,44,24
6,Ray Allen*,1454,228,190,57,1273,225,193,75
7,Tony Allen,379,56,89,35,494,114,134,34
8,Rafer Alston,1088,444,253,29,969,392,232,28
9,Lou Amundson,0,0,0,0,18,0,5,7
10,Lou Amundson,16,1,15,13,18,0,5,7
11,Derek Anderson,399,133,84,29,141,44,43,9
12,Carmelo Anthony,1881,249,248,143,1978,259,393,178
13,Gilbert Arenas,2105,443,277,61,252,66,45,6
14,Trevor Ariza,506,65,151,98,36,8,19,5
15,Trevor Ariza,506,65,151,98,156,36,59,25
16,Darrell Armstrong,457,191,101,34,123,73,50,17
17,Hilton Armstrong,176,10,91,58,178,23,98,65
18,Carlos Arroyo,552,202,103,31,430,219,103,10
19,Chucky Atkins,988,346,121,18,113,47,28,3
20,James Augustine,2,2,2,1,40,2,14,16
21,Kelenna Azubuike,291,28,68,26,692,75,217,107
22,Renaldo Balkman,334,44,197,97,224,40,133,83
23,Marcus Banks,221,60,28,10,125,25,17,3
24,Marcus Banks,221,60,28,10,114,36,24,1
25,Leandro Barbosa,1444,317,192,22,1283,216,191,40
26,J.J. Barea,78,24,18,7,191,58,43,4
27,Andrea Bargnani,751,50,203,52,792,89,238,50
28,Matt Barnes,746,156,259,91,486,139,230,94
29,Andre Barrett,8,7,4,1,6,7,1,0
30,Earl Barron,65,5,22,19,326,29,131,67
31,Brent Barry,635,138,143,17,221,54,43,12
32,Brandon Bass,42,3,30,13,654,58,227,120
33,Maceo Baston,138,16,53,21,41,3,17,9
34,Shane Battier,829,175,271,67,744,155,276,131
35,Charlie Bell,1110,247,181,57,514,210,136,31
36,Raja Bell,1143,196,203,48,889,168,227,47
37,Mike Bibby,1403,388,224,39,203,75,45,11
38,Mike Bibby,1403,388,224,39,464,215,99,5

In [61]:
SevenEightTPts = SevenEight["points_x"] + SevenEight["points_y"]
SevenEight["Total Points"] = SevenEightTPts
SevenEight.head()

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y,total points,Total Points
0,Shareef Abdur-Rahim,793,109,276,122,10,4,4,6,803,803
1,Maurice Ager,69,7,20,1,15,4,3,1,84,84
2,Maurice Ager,69,7,20,1,36,4,6,3,105,105
3,LaMarcus Aldridge,565,24,168,144,1350,122,358,220,1915,1915
4,Malik Allen,242,16,77,42,261,29,86,42,503,503

In [63]:
SevenEightDRbs = SevenEight["defensive_rebounds_x"] + SevenEight["defensive_rebounds_y"]
SevenEight["Total Defensive Rebounds"] = SevenEightDRbs
SevenEight.head()

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y,total points,Total Points,Total Defensive Rebounds
0,Shareef Abdur-Rahim,793,109,276,122,10,4,4,6,803,803,280
1,Maurice Ager,69,7,20,1,15,4,3,1,84,84,23
2,Maurice Ager,69,7,20,1,36,4,6,3,105,105,26
3,LaMarcus Aldridge,565,24,168,144,1350,122,358,220,1915,1915,526
4,Malik Allen,242,16,77,42,261,29,86,42,503,503,163

In [64]:
SevenEightORbs = SevenEight["offensive_rebounds_x"] + SevenEight["offensive_rebounds_y"]
SevenEight["Total Offensive Rebounds"] = SevenEightORbs
SevenEight.head()

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y,total points,Total Points,Total Defensive Rebounds,Total Offensive Rebounds
0,Shareef Abdur-Rahim,793,109,276,122,10,4,4,6,803,803,280,128
1,Maurice Ager,69,7,20,1,15,4,3,1,84,84,23,2
2,Maurice Ager,69,7,20,1,36,4,6,3,105,105,26,4
3,LaMarcus Aldridge,565,24,168,144,1350,122,358,220,1915,1915,526,364
4,Malik Allen,242,16,77,42,261,29,86,42,503,503,163,84

In [67]:
SevenEightTotalAssists = SevenEight["assists_x"] + SevenEight["assists_y"]
SevenEight["Total Asists"] = SevenEightTotalAssists
SevenEight.head()

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y,total points,Total Points,Total Defensive Rebounds,Total Offensive Rebounds,Total Asists
0,Shareef Abdur-Rahim,793,109,276,122,10,4,4,6,803,803,280,128,113
1,Maurice Ager,69,7,20,1,15,4,3,1,84,84,23,2,11
2,Maurice Ager,69,7,20,1,36,4,6,3,105,105,26,4,11
3,LaMarcus Aldridge,565,24,168,144,1350,122,358,220,1915,1915,526,364,146
4,Malik Allen,242,16,77,42,261,29,86,42,503,503,163,84,45

In [71]:
SevenEightTRebounds = SevenEight["Total Defensive Rebounds"] + SevenEight["Total Offensive Rebounds"]
SevenEight.head()

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y,total points,Total Points,Total Defensive Rebounds,Total Offensive Rebounds,Total Asists
0,Shareef Abdur-Rahim,793,109,276,122,10,4,4,6,803,803,280,128,113
1,Maurice Ager,69,7,20,1,15,4,3,1,84,84,23,2,11
2,Maurice Ager,69,7,20,1,36,4,6,3,105,105,26,4,11
3,LaMarcus Aldridge,565,24,168,144,1350,122,358,220,1915,1915,526,364,146
4,Malik Allen,242,16,77,42,261,29,86,42,503,503,163,84,45

In [69]:
OhNinestats = pd.read_csv("stats_2009.csv", engine='python')
OhNinestats

,attempted_three_point_field_goals,blocks,slug,personal_fouls,made_three_point_field_goals,attempted_field_goals,made_free_throws,name,minutes_played,turnovers,...,games_started,age,steals,team,points,attempted_free_throws,games_played,assists,offensive_rebounds,defensive_rebounds
0,4,1,ackeral01,0,0,11,1,Alex Acker,20,0,...,0,26,2,Team.DETROIT_PISTONS,9,2,7,1,0,2
1,16,3,ackeral01,9,7,65,4,Alex Acker,179,7,...,0,26,3,Team.LOS_ANGELES_CLIPPERS,63,8,18,11,8,14
2,0,1,adamsha01,4,0,13,3,Hassan Adams,52,4,...,0,24,1,Team.TORONTO_RAPTORS,11,6,12,1,1,6
3,107,13,afflaar01,144,43,300,58,Arron Afflalo,1234,43,...,8,23,28,Team.DETROIT_PISTONS,363,71,74,44,30,104
4,6,2,agerma01,17,0,43,4,Maurice Ager,97,4,...,0,24,1,Team.NEW_JERSEY_NETS,34,8,20,3,3,7
5,4,0,ahearbl01,3,2,6,2,Blake Ahearn,19,1,...,0,24,1,Team.SAN_ANTONIO_SPURS,8,2,3,2,0,1
6,2,6,ajincal01,34,0,69,20,Alexis AjinÃ§a,182,12,...,4,20,7,Team.CHARLOTTE_BOBCATS,70,28,31,3,9,21
7,28,77,aldrila01,207,7,1243,261,LaMarcus Aldridge,3004,121,...,81,23,77,Team.PORTLAND_TRAIL_BLAZERS,1470,334,81,157,234,371
8,46,29,alexajo01,107,16,245,58,Joe Alexander,716,52,...,0,22,15,Team.MILWAUKEE_BUCKS,278,83,59,42,44,71
9,1,12,allenma01,89,0,170,10,Malik Allen,579,20,...,3,30,7,Team.MILWAUKEE_BUCKS,156,21,49,35,35,68
10,486,13,allenra02,157,199,1040,237,Ray Allen*,2876,134,...,79,33,69,Team.BOSTON_CELTICS,1434,249,79,218,66,212
11,27,23,allento01,98,6,284,79,Tony Allen,887,77,...,2,27,54,Team.BOSTON_CELTICS,359,109,46,66,22,82
12,17,4,almonmo01,31,5,81,21,Morris Almond,255,16,...,1,23,4,Team.UTAH_JAZZ,92,26,25,7,9,27
13,230,7,alstora01,72,80,522,86,Rafer Alston,1591,88,...,48,32,57,Team.HOUSTON_ROCKETS,552,109,48,258,25,119
14,101,3,alstora01,63,32,298,70,Rafer Alston,856,52,...,28,32,51,Team.ORLANDO_MAGIC,348,99,29,148,8,75
15,1,65,amundlo01,154,0,250,53,Lou Amundson,1044,56,...,0,26,32,Team.PHOENIX_SUNS,321,120,76,28,128,142
16,10,175,anderch01,174,2,292,130,Chris Andersen,1460,69,...,1,30,41,Team.DENVER_NUGGETS,452,181,71,31,163,279
17,189,20,anderry01,157,69,407,98,Ryan Anderson,1312,63,...,30,20,44,Team.NEW_JERSEY_NETS,487,116,66,52,104,207
18,170,24,anthoca01,195,63,1207,371,Carmelo Anthony,2277,199,...,66,24,75,Team.DENVER_NUGGETS,1504,468,66,222,106,344
19,0,93,anthojo01,139,0,118,30,Joel Anthony,1048,41,...,28,26,20,Team.MIAMI_HEAT,144,46,65,27,89,108
20,7,1,arenagi01,4,2,23,12,Gilbert Arenas,63,1,...,2,27,0,Team.WASHINGTON_WIZARDS,26,16,2,20,1,8
21,191,24,arizatr01,166,61,596,120,Trevor Ariza,1999,87,...,20,23,137,Team.LOS_ANGELES_LAKERS,729,169,82,145,111,241
22,2,45,armsthi01,181,0,246,62,Hilton Armstrong,1092,80,...,29,24,26,Team.NEW_ORLEANS_HORNETS,338,98,70,29,81,114
23,2,52,arthuda01,206,0,436,40,Darrell Arthur,1464,47,...,64,20,52,Team.MEMPHIS_GRIZZLIES,422,60,76,43,108,238
24,17,1,atkinch01,5,5,27,4,Chucky Atkins,115,10,...,0,34,2,Team.DENVER_NUGGETS,27,4,14,28,0,6
25,40,1,atkinch01,22,10,86,11,Chucky Atkins,297,13,...,0,34,8,Team.OKLAHOMA_CITY_THUNDER,71,12,19,31,5,13
26,246,2,augusdj01,140,108,621,208,D.J. Augustin,1908,119,...,12,21,42,Team.CHARLOTTE_BOBCATS,850,233,72,250,17,116
27,210,50,azubuke01,183,94,845,185,Kelenna Azubuike,2375,95,...,51,25,57,Team.GOLDEN_STATE_WARRIORS,1063,229,74,117,112,258
28,7,23,balkmre01,98,2,197,42,Renaldo Balkman,780,35,...,10,24,47,Team.DENVER_NUGGETS,264,65,53,34,86,117
29,14,2,banksma01,21,2,39,10,Marcus Banks,166,11,...,0,27,10,Team.MIAMI_HEAT,42,15,16,22,0,15
30,5,0,banksma01,5,1,18,1,Marcus Banks,40,3,...,0,27,1,Team.TORONTO_RAPTORS,14,3,6,6,1,2
31,240,7,barbole01,115,90,759,171,Leandro Barbosa,1705,93,...,11,26,82,Team.PHOENIX_SUNS,993,194,70,162,34,147
32,154,5,bareajo01,121,55,557,70,J.J. Barea,1600,105,...,15,24,37,Team.DALLAS_MAVERICKS,617,93,79,269,36,141
33,291,97,bargnan01,242,119,958,221,Andrea Bargnani,2453,135,...,59,23,34,Team.TORONTO_RAPTORS,1202,266,78,94,70,346
34,341,26,barnema02,209,117,674,101,Matt Barnes,2082,130,...,40,28,52,Team.PHOENIX_SUNS,788,136,77,212,79,342
35,131,3,barrybr01,45,49,172,19,Brent Barry,857,48,...,1,37,24,Team.HOUSTON_ROCKETS,208,20,56,78,17,77
36,6,55,bassbr01,140,0,508,182,Brandon Bass,1574,86,...,0,23,27,Team.DALLAS_MAVERICKS,686,210,81,43,129,238
37,1,10,bastoma01,39,0,46,17,Maceo Baston,217,12,...,0,33,6,Team.INDIANA_PACERS,67,27,27,7,22,30
38,9,25,battito01,112,2,323,54,Tony Battie,1202,46,...,3,32,26,Team.ORLANDO_MAGIC,372,82,77,31,92,186
39,237,54,battish01,114,91,354,55,Shane Battier,2031,49,...,59,30,48,Team.HOUSTON_ROCKETS,436,67,60,137,52,233
40,168,40,batumni01,139,62,361,42,Nicolas Batum,1454,50,...,76,20,50,Team.PORTLAND_TRAIL_BLAZERS,426,52,79,74,84,136
41,27,2,bayleje01,81,7,189,83,Jerryd Bayless,655,56,...,0,20,16,Team.PORTLAND_TRAIL_BLAZERS,228,103,53,78,8,49
42,81,37,beaslmi01,184,33,957,186,Michael Beasley,2009,121,...,19,20,41,Team.MIAMI_HEAT,1123,241,81,83,110,329
43,131,1,belinma01,73,52,317,40,Marco Belinelli,882,59,...,23,22,36,Team.GOLDEN_STATE_WARRIORS,372,52,42,88,10,61
44,240,7,bellch01,138,87,524,66,Charlie Bell,1783,76,...,23,29,50,Team.MILWAUKEE_BUCKS,587,80,70,151,32,102
45,94,2,bellra01,57,44,177,16,Raja Bell,712,18,...,22,32,13,Team.PHOENIX_SUNS,212,21,22,29,8,56
46,177,6,bellra01,109,70,507,71,Raja Bell,1603,68,...,44,32,37,Team.CHARLOTTE_BOBCATS,587,81,45,113,33,146
47,428,11,bibbymi01,145,167,1005,135,Mike Bibby,2740,128,...,79,30,98,Team.ATLANTA_HAWKS,1176,171,79,392,38,240

In [75]:
SevenEightNine = pd.merge(SevenEight, OhNinestats, on=['name'])
SevenEightNine.head()

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y,total points,...,games_started,age,steals,team,points,attempted_free_throws,games_played,assists,offensive_rebounds,defensive_rebounds
0,Maurice Ager,69,7,20,1,15,4,3,1,84,...,0,24,1,Team.NEW_JERSEY_NETS,34,8,20,3,3,7
1,Maurice Ager,69,7,20,1,36,4,6,3,105,...,0,24,1,Team.NEW_JERSEY_NETS,34,8,20,3,3,7
2,LaMarcus Aldridge,565,24,168,144,1350,122,358,220,1915,...,81,23,77,Team.PORTLAND_TRAIL_BLAZERS,1470,334,81,157,234,371
3,Malik Allen,242,16,77,42,261,29,86,42,503,...,3,30,7,Team.MILWAUKEE_BUCKS,156,21,49,35,35,68
4,Malik Allen,242,16,77,42,77,15,44,24,319,...,3,30,7,Team.MILWAUKEE_BUCKS,156,21,49,35,35,68

In [101]:
SevenEightNineTpoints = SevenEight["total points"] + OhNinestats["points"]
SevenEightNine["Total baskets"] = SevenEightNineTpoints
SevenEightNine.head()
OhNinestats['points']
print(SevenEightNineTpoints.head())
print(SevenEight['total points'].head())
print(OhNinestats["points"].head())

0      93.0
1     168.0
2    1926.0
3     866.0
4     353.0
dtype: float64
0     803
1      84
2     105
3    1915
4     503
Name: total points, dtype: int64
0      9
1     63
2     11
3    363
4     34
Name: points, dtype: int64

In [103]:
SevenEightNineTpoints = SevenEightNine["total points"] + SevenEightNine["points"]
SevenEightNineTpoints.head()

0     118
1     139
2    3385
3     659
4     475
dtype: int64

In [105]:
SevenEightNine["Total points overall"] = SevenEightNineTpoints
SevenEightNine.head()

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y,total points,...,steals,team,points,attempted_free_throws,games_played,assists,offensive_rebounds,defensive_rebounds,Total baskets,Total points overall
0,Maurice Ager,69,7,20,1,15,4,3,1,84,...,1,Team.NEW_JERSEY_NETS,34,8,20,3,3,7,93.0,118
1,Maurice Ager,69,7,20,1,36,4,6,3,105,...,1,Team.NEW_JERSEY_NETS,34,8,20,3,3,7,168.0,139
2,LaMarcus Aldridge,565,24,168,144,1350,122,358,220,1915,...,77,Team.PORTLAND_TRAIL_BLAZERS,1470,334,81,157,234,371,1926.0,3385
3,Malik Allen,242,16,77,42,261,29,86,42,503,...,7,Team.MILWAUKEE_BUCKS,156,21,49,35,35,68,866.0,659
4,Malik Allen,242,16,77,42,77,15,44,24,319,...,7,Team.MILWAUKEE_BUCKS,156,21,49,35,35,68,353.0,475

In [106]:
SevenEightNineTDrebounds = SevenEightNine["defensive_rebounds_x"] + SevenEightNine["defensive_rebounds_y"] + SevenEightNine["defensive_rebounds"]
SevenEightNineTDrebounds.head()

0     30
1     33
2    897
3    231
4    189
dtype: int64

In [107]:
SevenEightNine["Total defensive rebounds"] = SevenEightNineTDrebounds
SevenEightNine.head()

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y,total points,...,team,points,attempted_free_throws,games_played,assists,offensive_rebounds,defensive_rebounds,Total baskets,Total points overall,Total defensive rebounds
0,Maurice Ager,69,7,20,1,15,4,3,1,84,...,Team.NEW_JERSEY_NETS,34,8,20,3,3,7,93.0,118,30
1,Maurice Ager,69,7,20,1,36,4,6,3,105,...,Team.NEW_JERSEY_NETS,34,8,20,3,3,7,168.0,139,33
2,LaMarcus Aldridge,565,24,168,144,1350,122,358,220,1915,...,Team.PORTLAND_TRAIL_BLAZERS,1470,334,81,157,234,371,1926.0,3385,897
3,Malik Allen,242,16,77,42,261,29,86,42,503,...,Team.MILWAUKEE_BUCKS,156,21,49,35,35,68,866.0,659,231
4,Malik Allen,242,16,77,42,77,15,44,24,319,...,Team.MILWAUKEE_BUCKS,156,21,49,35,35,68,353.0,475,189

In [109]:
SevenEightNineTOrebounds = SevenEightNine["offensive_rebounds_x"] + SevenEightNine["offensive_rebounds_y"] + SevenEightNine["offensive_rebounds"]
SevenEightNineTOrebounds.head()

0      5
1      7
2    598
3    119
4    101
dtype: int64

In [110]:
SevenEightNine["Total offensive rebounds"] = SevenEightNineTOrebounds
SevenEightNine.head()

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y,total points,...,points,attempted_free_throws,games_played,assists,offensive_rebounds,defensive_rebounds,Total baskets,Total points overall,Total defensive rebounds,Total offensive rebounds
0,Maurice Ager,69,7,20,1,15,4,3,1,84,...,34,8,20,3,3,7,93.0,118,30,5
1,Maurice Ager,69,7,20,1,36,4,6,3,105,...,34,8,20,3,3,7,168.0,139,33,7
2,LaMarcus Aldridge,565,24,168,144,1350,122,358,220,1915,...,1470,334,81,157,234,371,1926.0,3385,897,598
3,Malik Allen,242,16,77,42,261,29,86,42,503,...,156,21,49,35,35,68,866.0,659,231,119
4,Malik Allen,242,16,77,42,77,15,44,24,319,...,156,21,49,35,35,68,353.0,475,189,101

In [111]:
SevenEightNineTAssists = SevenEightNine["assists_x"] + SevenEightNine["assists_y"] + SevenEightNine["assists"]
SevenEightNineTAssists.head()

0     14
1     14
2    303
3     80
4     66
dtype: int64

In [112]:
SevenEightNine["Total assists"] = SevenEightNineTAssists
SevenEightNine.head()

,name,points_x,assists_x,defensive_rebounds_x,offensive_rebounds_x,points_y,assists_y,defensive_rebounds_y,offensive_rebounds_y,total points,...,attempted_free_throws,games_played,assists,offensive_rebounds,defensive_rebounds,Total baskets,Total points overall,Total defensive rebounds,Total offensive rebounds,Total assists
0,Maurice Ager,69,7,20,1,15,4,3,1,84,...,8,20,3,3,7,93.0,118,30,5,14
1,Maurice Ager,69,7,20,1,36,4,6,3,105,...,8,20,3,3,7,168.0,139,33,7,14
2,LaMarcus Aldridge,565,24,168,144,1350,122,358,220,1915,...,334,81,157,234,371,1926.0,3385,897,598,303
3,Malik Allen,242,16,77,42,261,29,86,42,503,...,21,49,35,35,68,866.0,659,231,119,80
4,Malik Allen,242,16,77,42,77,15,44,24,319,...,21,49,35,35,68,353.0,475,189,101,66