In [2]:
#Import dependencies
import pandas as pd
import datetime as dt

In [3]:
nba_draft = pd.read_csv("2007-2016_nba_draft_rd1-2.csv", engine='python')
nba_draft.head()

,Rk,Year,Lg,Rd,Pk,Tm,Player,Age,Pos,Born,...,TRB,AST,STL,BLK,FG%,2P%,3P%,FT%,WS,WS/48
0,1,2007,NBA,1,2,SEA,Kevin Durant,18.276,F-G,us,...,7.1,4.1,1.1,1.1,0.493,0.532,0.381,0.883,141.7,0.217
1,2,2009,NBA,1,3,OKC,James Harden,19.308,G,us,...,5.3,6.3,1.6,0.5,0.443,0.508,0.364,0.858,131.9,0.226
2,3,2009,NBA,1,7,GSW,Stephen Curry,21.108,G,us,...,4.5,6.6,1.7,0.2,0.476,0.515,0.435,0.905,103.1,0.206
3,4,2008,NBA,1,4,SEA,Russell Westbrook,19.231,G,us,...,7.1,8.3,1.7,0.3,0.436,0.468,0.304,0.801,100.5,0.161
4,5,2007,NBA,1,3,ATL,Al Horford,21.030,C-F,do,...,8.3,3.3,0.8,1.2,0.520,0.544,0.361,0.753,89.8,0.158

In [4]:
draft_condensed = nba_draft[["Player", "Year", "Tm", "College"]]
draft_condensed.head()

              Player  Year   Tm        College
0       Kevin Durant  2007  SEA          Texas
1       James Harden  2009  OKC  Arizona State
2      Stephen Curry  2009  GSW       Davidson
3  Russell Westbrook  2008  SEA           UCLA
4         Al Horford  2007  ATL        Florida

In [5]:
#Can convert to list by adding .values.tolist() at the end of each
first_year = draft_condensed.loc[draft_condensed["Year"] == 2007].copy()
second_year = draft_condensed.loc[draft_condensed["Year"] == 2008].copy()
third_year = draft_condensed.loc[draft_condensed["Year"] == 2009].copy()
fourth_year = draft_condensed.loc[draft_condensed["Year"] == 2010].copy()
fifth_year = draft_condensed.loc[draft_condensed["Year"] == 2011].copy()
sixth_year = draft_condensed.loc[draft_condensed["Year"] == 2012].copy()
seventh_year = draft_condensed.loc[draft_condensed["Year"] == 2013].copy()
eighth_year = draft_condensed.loc[draft_condensed["Year"] == 2014].copy()
ninth_year = draft_condensed.loc[draft_condensed["Year"] == 2015].copy()
tenth_year = draft_condensed.loc[draft_condensed["Year"] == 2016].copy()

                 Player  Year   Tm             College
0          Kevin Durant  2007  SEA               Texas
4            Al Horford  2007  ATL             Florida
6            Marc Gasol  2007  LAL                 NaN
12          Mike Conley  2007  MEM          Ohio State
20          Joakim Noah  2007  CHI             Florida
23       Thaddeus Young  2007  PHI        Georgia Tech
51         Jared Dudley  2007  CHA      Boston College
58           Jeff Green  2007  BOS          Georgetown
65          Carl Landry  2007  SEA              Purdue
70        Arron Afflalo  2007  DET                UCLA
77      Marco Belinelli  2007  GSW                 NaN
83      Wilson Chandler  2007  NYK              DePaul
85       Ramon Sessions  2007  MIL              Nevada
86       Rodney Stuckey  2007  DET  Eastern Washington
96       Brandan Wright  2007  CHA                 UNC
102      Tiago Splitter  2007  SAS                 NaN
116       Spencer Hawes  2007  SAC          Washington
118        Corey Brewer  2007  MIN             Florida
142        Aaron Brooks  2007  HOU              Oregon
145          Nick Young  2007  WAS                 USC
146          Glen Davis  2007  SEA                 LSU
148      Josh McRoberts  2007  POR                Duke
183      Rudy Fernï¿½ndez  2007  PHO                 NaN
184         Jason Smith  2007  MIA      Colorado State
246           Greg Oden  2007  POR          Ohio State
257          Aaron Gray  2007  CHI                Pitt
260         Al Thornton  2007  LAC       Florida State
278        Daequan Cook  2007  PHI          Ohio State
291     Dominic McGuire  2007  WAS        Fresno State
294       Julian Wright  2007  NOK              Kansas
312         Yi Jianlian  2007  MIL                 NaN
313       Sean Williams  2007  NJN      Boston College
340            Acie Law  2007  ATL           Texas A&M
360      Kyrylo Fesenko  2007  PHI                 NaN
365        Nick Fazekas  2007  DAL              Nevada
370       Chris Richard  2007  MIN             Florida
387       Alando Tucker  2007  PHO           Wisconsin
388         Gabe Pruitt  2007  BOS                 USC
395      Stï¿½phane Lasme  2007  GSW               UMass
420  Javaris Crittenton  2007  LAL        Georgia Tech
421       Derrick Byars  2007  POR          Vanderbilt
432       Morris Almond  2007  UTA     Rice University
433   Jermareo Davidson  2007  GSW             Alabama
434       JamesOn Curry  2007  CHI      Oklahoma State
458     Marcus Williams  2007  SAS             Arizona
459             Sun Yue  2007  LAL                 NaN
460       Taurean Green  2007  POR             Florida
479    Demetris Nichols  2007  POR            Syracuse
480     D.J. Strawberry  2007  PHO            Maryland
513     Petteri Koponen  2007  PHI                 NaN
514        Stanko Bara_  2007  MIA                 NaN
515        Adam Haluska  2007  NOK                Iowa
516      Reyshawn Terry  2007  ORL                 UNC
517        Jared Jordan  2007  LAC      Marist College
518   Renaldas Seibutis  2007  DAL                 NaN
519         Brad Newley  2007  HOU                 NaN
520        Herbert Hill  2007  UTA          Providence
521         Sammy Mejia  2007  DET              DePaul
522  Georgios Printezis  2007  SAS                 NaN
523      Milovan Rakovi  2007  DAL                 NaN